services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static-data:/app/static

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - BACKEND_BASE_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  static-data:
